language: ruby
sudo: required
dist: trusty
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3
script:
- rvm use --default $TRAVIS_RUBY_VERSION
- sed -i "/^ENV_SUPATH/s/PATH=/PATH=$MY_RUBY_HOME\/bin:/" /etc/login.defs
- sed -i "/^ENV_PATH/s/PATH=/PATH=$MY_RUBY_HOME\/bin:/" /etc/login.defs
- echo '#!/bin/bash' | sudo tee /etc/profile.d/rvm.sh
- echo 'export PATH="$PATH:/home/travis/.rvm/bin"' | sudo tee -a /etc/profile.d/rvm.sh
- echo 'source /home/travis/.rvm/scripts/rvm' | sudo tee -a /etc/profile.d/rvm.sh
- sudo chmod +x /etc/profile.d/rvm.sh
- bundle exec rake default
- bundle exec kitchen test
- sudo chown -R travis:travis /home/travis/.rvm
- gem build sensu-plugins-postfix.gemspec
- gem install sensu-plugins-postfix-*.gem
- cat /tmp/break
env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
